---
title: "Seabirds at Acadia Aquafarms"
subtitle: "Presentation subtitle (if any)"
author: "Jackie Brooks and Adler Garner"
institute: "College of the Atlantic"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r load-packages, include = FALSE}
# Add any additional packages you need to this chunk
library(tidyverse)
library(broom)
library(readxl)
library(dplyr)
#install.packages("ggridges")
library(ggridges)
```

```{r setup, include=FALSE}
# For better figure resolution
knitr::opts_chunk$set(fig.retina = 3, dpi = 300, fig.width = 6, fig.asp = 0.618, out.width = "80%")
```

```{r load-data, include=FALSE}
# Load your data here

#view(seabird_count_tidy)

```

```{r read_in_data}
seabird_count_tidy <- read_csv("../data/seabird_count_tidy.csv")
```

# Code

```{r boring-regression}
# a boring regression
model <- lm(dist ~ speed, data = cars)
tidy(model)
glance(model)
```

---

# Plots

```{r tide_and_count_graph, fig.alt = "Bar graph of the total number of birds present at different tidal levels seperated by year, over nine years, 2015-2023. We notice on average birds are seen more at high tide than low tide and significantly more than mid tide. In 2020, 2022, 2023 the difference in number of birds spotted at mid tide verus high tide was around 1500."}


seabird_count_tidy <- seabird_count_tidy %>%
  filter(!is.na(tide_obs)) %>% 
  mutate(
    tide_obs = fct_relevel(
      tide_obs, "low", "mid", "high"
    )
  )  
  
seabird_count_tidy |> filter(year %in% c(15, 16, 17, 18, 19, 20, 21, 22, 23)) %>% 
  group_by(tide_obs) %>% 
  ggplot(aes(x = fct_relevel(tide_obs), fill = tide_obs)) + 
     geom_bar() + 
     facet_wrap(~ year) +
    theme_linedraw() +
  scale_fill_viridis_d() + 
  labs(title = "Total Number of Birds Present at Different Tide Levels", subtitle = "Seperated by Year Over Nine Years 2015-2023", x = "Tide Observation", y = "Number of Birds ")

```


```{r observation_time_of_day, echo = FALSE}
seabird_time_of_day_count <- seabird_count_tidy %>% 
  distinct(date, time_of_day) %>% 
  mutate(year = str_sub(date, 1, 4)) %>% 
  filter(year %in% c(2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023)) 
  
seabird_time_of_day_count %>%
  filter(year > 14, year < 24) %>%
ggplot(aes(x = time_of_day, fill = time_of_day)) + 
     geom_bar() + 
  labs(x = "Time of Day", y = "Number of Observations", title = "Number of Observations Done at Different Times of the Day", subtitle = "2015 - 2023", fill = "Time of Day") +
  theme_linedraw() +
  theme(axis.text.x = element_blank()) +
  scale_fill_viridis_d() +
  facet_wrap(~ year)
```



```{r species_diversity_over_time_plot}
 seabird_count_tidy %>% 
  filter(!is.na(species_group), count > 0, year > 14, year < 24) %>% 
  ggplot(aes(x = year, y = count, color = species_group)) +
  geom_point(alpha = 0.75) +
  theme_linedraw() +
  scale_color_viridis_d() + 
  labs(title = "Total Amount of Birds Over Nine Years", subtitle = "2015-2023", x = "Year", y = "Total Number of Individual", color = "Species Group") +
  scale_x_continuous(breaks = seq(15, 23, by = 1))
```

```{r species_diversity_over_time_jitter_plot, fig.alt = "Jitter plot of the total amount of birds over nine years seperated by the species group, duck, gen_non_waterbird, gen_waterbird, grebe, gull, loon, and shorebird. This chart shows that the number of gull has increased thoughout the years dramatically going from around 90 to around 150 spotted at a time, at some points reaching over 300. Ducks and gen_waterbird increase less significantly going from around 20 to around 50 and 50 to 100 respeticvely, over the nine years. The rest don't show much change and have low numbers."}
 seabird_diversity_graph <- seabird_count_tidy %>%
  filter(!is.na(species_group), count > 0, year > 14, year < 24) %>% 
  ggplot(aes(x = year, y = count, color = species_group)) +
  geom_jitter(alpha = 0.75) +
  theme_linedraw() +
  scale_color_viridis_d() + 
  labs(title = "Total Amount of Birds Over Nine Years", subtitle = "2015-2023", x = "Year", y = "Total Number of Individual", color = "Species Group") +
  scale_x_continuous(breaks = seq(15, 23, by = 1))

ggsave("seabird_diversity_graph.jpeg", seabird_diversity_graph, device = "jpeg", width = 10, height = 8)
```

```{r bird_spotting_condition, fig.alt = "Density plot of temperature and weather oberservations seperated by species group, duck, gen_non_waterbird, gen_waterbird, grebe, gull, loon, and shorebird. The charts show that grebes are not present here in the summer, we don't see many birds past 75 degrees or below 20 other than the major outlier in gen_waterbird. Gen_non_waterbird has a bimodal graph peaking twice at around 30 degrees and again at around 70. Shorebirds shows no data since there were no observations that fit the description."}
seabird_condition_graph <- seabird_count_tidy %>% 
  filter(!is.na(weather_obs), !is.na(species_group), count > 0, year > 14, year < 24) %>%
  filter(species_group %in% c("duck", "gen_non_waterbird", "gen_waterbird", "grebe", "gull", "loon", "shorebird")) %>%
  ggplot(aes(x = temp, y = weather_obs, fill = season)) +
  geom_density_ridges(alpha = 0.75) +
  theme_linedraw() +
  scale_fill_viridis_d() +
  facet_wrap(~ species_group, scales = "free_x") +
  xlim(0, 95) +
  labs(title = "Temperature and Weather Conditions of When Species of Birds are Spotted", subtitle = "2015-2023", x = "Temperature", y = "Weather Condition", color = "Season") 
 
ggsave("seabird_condition_graph.jpeg", seabird_condition_graph, device = "jpeg", width = 10, height = 8) 
```

```{r species_count_vs_wind_direction_plot, fig.alt = "Bar plot of the number of birds recorded in a day and the recorded wind direction. Between the four main cardinal directions (north, south, east, and west), there are more birds seen when the wind is blowing south or west than north or east."}

seabird_count_tidy %>%
  filter(species == "total") %>%
  filter(is.na(wind_direction_new) == FALSE) %>% 
  filter(year > 14, year < 24) %>%
  ggplot(aes(x = wind_direction_new, y = count, fill = wind_direction_new)) + 
  geom_col() +
  scale_fill_viridis_d() +
  labs(x = "Wind Direction", y = "Number of Birds", title = "Number of Birds per Day by Wind Direction", fill = "Wind Direction", subtitle = "2015 - 2023") +
  theme_linedraw()

```

```{r species_count_vs_wind_direction_by_wind_speed_plot, fig.alt = "Segmented bar plot of the number of birds recorded in a day and the recorded wind direction, coloured by the recorded wind speed in MPH. Between the four main cardinal directions (north, south, east, and west), there are more birds seen when the wind is blowing south or west than north or east. In terms of wind speed, there seem to me the most birds present at wind speeds between 5 and 15 MPH."}

seabird_count_tidy <- seabird_count_tidy %>%
  mutate(wind_speed_group = case_when(wind_speed_new >= 0 & wind_speed_new <= 4.9 ~ "0 - 4.9",
                                      wind_speed_new >= 5 & wind_speed_new <= 9.9 ~ "5 - 9.9",
                                      wind_speed_new >= 10 & wind_speed_new <= 14.9 ~ "10 - 14.9",
                                      wind_speed_new <= 15 & wind_speed_new <= 19.9 ~ "15 - 19.9",
                                      wind_speed_new >= 20 & wind_speed_new <= 24.9 ~ "20 - 24.9",
                                      wind_speed_new >= 25 & wind_speed_new <= 29.9 ~ "25 - 29.9",
                                      wind_speed_new == 30 ~ "0 - 4.9",))

seabird_count_tidy %>%
  filter(species == "total") %>%
  filter(is.na(wind_direction_new) == FALSE) %>% 
  filter(year > 14, year < 24) %>%
  ggplot(aes(x = wind_direction_new, y = count, fill = wind_speed_group)) + 
  geom_col() +
  scale_fill_viridis_d() +
  labs(x = "Wind Direction", y = "Number of Birds", title = "Number of Birds per Day by Wind Direction", fill = "Wind Speed (mph)", subtitle = "2015 - 2023") +
  theme_linedraw()

```

```{r species_count_and_wind_speed_plot, fit.alt = "Jitter plot of the number of birds recorded in a day and the recorded wind speed (in MPH). According to the graph, there appear to be a higher frequency of birds present at wind speeds below 15 MPH."}

seabird_count_tidy %>%
  filter(species == "total") %>%
  filter(year > 14, year < 24) %>%
  ggplot(aes(x = wind_speed_new, y = count, colour = wind_speed_new)) +
  labs(x = "Wind Speed (mph)", y = "Number of Birds", colour = "Wind Speed (mph)", title = "Number of Birds per Day by Wind Speed", subtitle = "2015 - 2023") +  
  geom_jitter(width = 1.3, alpha = 0.9) +
  geom_smooth(method = "lm", colour = "black", size = 0.7) +
  theme_linedraw() +
  scale_colour_viridis_c(option = "turbo")

```

```{r number_of_geese_at_goose_cove}
canada_geese <- seabird_count_tidy %>% 
  filter(species == "canada_goose")

sum(canada_geese$count)
```


